### ISSUE TITLE
Exponential Edge Case in Parser

### ISSUE THREAD

**Issue by stephenmac7** [kowainik/tomland#195] opened 2019-06-11 20:30 UTC
Parsing the file below takes 6 seconds on my machine, even though it's pretty small. Might be an issue with backtracking in the parser. For more complicated files, there is exponential blowup.

```
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
[[a]]
```

**Comment by chshersh** [comment] 2019-06-12 06:19
@stephenmac7 Thanks for reporting the problem! Parsing TOML files is indeed not that simple, because parsing should be context-sensitive, unfortunately, in the current implementation. Though I have some ideas on how to improve the situation, I will try to look into this problem and see what can be done.

**Comment by jiegillet** [comment] 2019-06-12 06:28
I played around and can confirm the issue. Unfortunately I can't think of a quick fix, but I'll look into it too.

**Comment by nhibberd** [comment] 2019-06-12 18:06
If its useful, I have made an attempt at a fix here (not complete but progress) - https://github.com/kowainik/tomland/compare/master...nhibberd:master

**Comment by chshersh** [comment] 2019-06-13 04:40
@nhibberd Thanks for your attempt to fix the problem! I would say that if tests are passing and if the example from this issue is parsed without performance issues, then the PR can be merged. We have quite exhaustive test-suite, though adding a couple more tests never hurts :slightly_smiling_face:

**Comment by stephenmac7** [comment] 2019-06-13 17:42
The fork @nhibberd posted fixed my issue, but the tests don't pass.

**Comment by chshersh** [comment] 2019-06-27 02:41
The issue is fixed by @jiegillet. It's already in `master`.

**Closed by chshersh** 2019-06-27 02:41 UTC
Labels: help wanted, performance
